#!/bin/sh
# Run Rust formatting and linting
cargo fmt --manifest-path src-tauri/Cargo.toml
cargo clippy --fix --manifest-path src-tauri/Cargo.toml --allow-dirty --allow-staged

# Run lint-staged for frontend files
npx lint-staged