#!/bin/sh
# Run Rust formatting and linting
cargo clippy --fix --manifest-path src-tauri/Cargo.toml --allow-dirty --allow-staged
cargo fmt --manifest-path src-tauri/Cargo.toml

# Run lint-staged for frontend files
npx lint-staged